### ISSUE TITLE
Incorrect license (again)

### ISSUE THREAD

**Issue by Nihlus** [pauldotknopf/net-native-lib-loader#2]
The new license of the project is GPLv3 - which I wholly support, in case it was intentional - which is more restrictive than the LGPL. I suspect this was not the intent, and that the intent was to apply the LGPLv3 instead.

https://github.com/pauldotknopf/net-native-lib-loader/blob/master/LICENSE

**Comment by pauldotknopf** [comment]
Damnit, I meant to do that one. Give me a sec.

**Comment by Perksey** [comment]
XD Shit happens :P

**Comment by pauldotknopf** [comment]
Fixed.
